[
  {
    react:
      "const AnimatedHeatmap = () => {\n  // Create a 7x54 grid (7 days x 54 weeks) to match GitHub contribution graph\n  const rows = 7; // Days of the week\n  const cols = 54; // Weeks\n  \n  // Define the positions for each letter in",
    ASHWIN:
      "Each letter is represented as a 7x5 grid pattern\n  const letterPatterns: Record<string",
    A: [
      [0, 1, 1, 1, 0],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
    ],
    S: [
      [0, 1, 1, 1, 1],
      [1, 0, 0, 0, 0],
      [1, 0, 0, 0, 0],
      [0, 1, 1, 1, 0],
      [0, 0, 0, 0, 1],
      [0, 0, 0, 0, 1],
      [1, 1, 1, 1, 0],
    ],
    H: [
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 1, 1, 1, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
    ],
    W: [
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 1, 0, 1],
      [1, 0, 1, 0, 1],
      [1, 1, 0, 1, 1],
      [1, 0, 0, 0, 1],
    ],
    I: [
      [1, 1, 1, 1, 1],
      [0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0],
      [1, 1, 1, 1, 1],
    ],
    N: [
      [1, 0, 0, 0, 1],
      [1, 1, 0, 0, 1],
      [1, 0, 1, 0, 1],
      [1, 0, 0, 1, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
      [1, 0, 0, 0, 1],
    ],
  },
  { row: "number; col: number" },
  [],
  {},
  [
    "letter, pattern] of Object.entries(letterPatterns)) {\n    const positions = [];\n    for (let r = 0; r < pattern.length; r++) {\n      for (let c = 0; c < pattern[r].length; c++) {\n        if (pattern[r][c] === 1) {\n          positions.push({\n            row: r + startY,\n            col: c + currentX,\n          });\n        }\n      }\n    }\n    letterPositions[letter] = positions;\n    currentX += pattern[0].length + letterSpacing; // Move to next letter position\n  }\n\n  // Flatten all letter positions into a single array\n  const allLetterPositions = Object.values(letterPositions).flat();\n  \n  const [grid, setGrid] = useState<boolean[][]>([]);\n  const [animationStep, setAnimationStep] = useState(0);\n  \n  // Initialize grid\n  useEffect(() => {\n    const initialGrid: boolean[][] = Array(rows)\n      .fill(null)\n      .map(() => Array(cols).fill(false));\n    \n    setGrid(initialGrid);\n  }, []);\n  \n  // Animation effect\n  useEffect(() => {\n    if (grid.length === 0) return;\n    \n    const interval = setInterval(() => {\n      setAnimationStep(prev => prev + 1);\n    }, 100);\n    \n    return () => clearInterval(interval);\n  }, [grid]);\n  \n  // Update grid based on animation step\n  useEffect(() => {\n    if (grid.length === 0 || animationStep === 0) return;\n    \n    const newGrid = [...grid.map(row => [...row])];\n    const totalCells = allLetterPositions.length;\n    const cellsToActivate = Math.min(animationStep, totalCells);\n    \n    for (let i = 0; i < cellsToActivate; i++) {\n      const pos = allLetterPositions[i];\n      if (pos) {\n        newGrid[pos.row][pos.col] = true;\n      }\n    }\n    \n    setGrid(newGrid);\n  }, [animationStep, grid]);\n  \n  // Get color based on cell state\n  const getCellColor = (row: number, col: number) => {\n    // Check if this cell is part of any letter\n    const isLetterCell = allLetterPositions.some(\n      pos => pos.row === row && pos.col === col\n    );\n    \n    if (!isLetterCell) {\n      return 'bg-gray-800'; // Default dark background\n    }\n    \n    if (grid[row]?.[col]) {\n      // Animated color based on position for a rainbow effect\n      const positionIndex = allLetterPositions.findIndex(\n        pos => pos.row === row && pos.col === col\n      );\n      const colors = [\n        'bg-green-400',\n        'bg-green-500',\n        'bg-green-600',\n        'bg-green-700',\n        'bg-green-800',\n      ];\n      return colors[positionIndex % colors.length];\n    }\n    \n    return 'bg-gray-900'; // Letter cell but not activated yet\n  };\n  \n  return (\n    <div className=\"flex flex-col items-center justify-center p-8 bg-gray-950 rounded-xl\">\n      <h2 className=\"text-2xl font-bold text-white mb-6\">ASHWIN</h2>\n      <div className=\"flex flex-col items-center\">\n        {/* GitHub-style contribution grid */}\n        <div className=\"flex flex-col gap-1",
    { length: "rows" },
    ".",
    'map((_, rowIndex) => (\n            <div key={rowIndex} className="flex gap-1',
    { length: "cols" },
    ".",
    'map((_, colIndex) => (\n                <div\n                  key={`${rowIndex}-${colIndex}`}\n                  className={`w-3 h-3 rounded-sm transition-colors duration-300 ${getCellColor(rowIndex, colIndex)}`}\n                />\n              ))}\n            </div>\n          ))}\n        </div>\n        <p className="text-gray-500 text-sm mt-4',
    "Animated GitHub-style contribution heatmap\n        </p>\n      </div>\n    </div>\n  );\n};\n\nexport default AnimatedHeatmap;",
  ],
];